#!/usr/bin/env ruby
#check dns resolution against a static host/ip
#the result should always be the same any change is a concern
#this will monitor our DNS forwarding
require 'resolv'
require 'timeout'

DEFAULT_TIMEOUT=2

#perform dns resoltion
#TODO: timing support, expanded results
def resolve_host(name, timeout_s: DEFAULT_TIMEOUT)
  a, aaaa = [], []
  elapsed_ms = nil
  status = 'NOERROR'
  t0 = Time.now

  begin
    Timeout.timeout(timeout_s) do
      dns = Resolv::DNS.new # will use the "system" dns server
      a     = dns.getresources(name, Resolv::DNS::Resource::IN::A).map { |r| r.address.to_s }
      aaaa  = dns.getresources(name, Resolv::DNS::Resource::IN::AAAA).map { |r| r.address.to_s }
      status = if a.empty? && aaaa.empty?
                 'NOANSWER'
               else
                 'NOERROR'
               end
    end
  rescue Timeout::Error
    status = 'TIMEOUT'
    print "#{status}"
    exit(1)
  rescue Resolv::ResolvError
    status = 'NXDOMAIN'
    print "#{status}"
    exit(1)
  rescue => e
    status = "ERROR(#{e.class})"
    print "#{status}"
    exit(1)
  ensure
    elapsed_ms = ((Time.now - t0) * 1000).round
  end

  { name: name, a: a.uniq.sort, aaaa: aaaa.uniq.sort, status: status, time_ms: elapsed_ms }
end


result = resolve_host("ipv4.download1.thinkbroadband.com")

case result[:a].to_s
 when '["80.249.99.148"]'
        nagioscritical = 0
        print "Forwarding DNS returned #{result[:a]} expected [80.249.99.148]"
        exit(0)
 else
        nagioscritical = 1
        print "Fowarding DNS returned #{result[:a]} expected [80.249.99.148]"
        exit(1)
end

